export type JsonRecord = Record<string, unknown>;
export type DealFinderSearchProfile = {
  id: number; user_id: number; name: string; source_type: "kleinanzeigen_agent" | "manual_json" | "mock" | "email"; source_config?: JsonRecord | null; brand?: string | null; model?: string | null; category_id?: string | null; location_id?: string | null; location_name?: string | null; postal_code?: string | null; radius_km?: number | null; price_min?: number | null; price_max?: number | null; year_min?: number | null; year_max?: number | null; mileage_min?: number | null; mileage_max?: number | null; fuel_types?: string[]; transmissions?: string[]; seller_types?: string[]; required_keywords?: string[]; excluded_keywords?: string[]; picture_required?: boolean; minimum_deal_score?: number; sync_enabled?: boolean; sync_interval_minutes?: number | null; is_active?: boolean;
};
export type KleinanzeigenPrice = { amount?: number | null; currency_code?: string | null };
export type KleinanzeigenImage = { url?: string | null } | string;
export type KleinanzeigenAd = { ad_id?: string | number | null; title?: string | null; description?: string | null; price?: KleinanzeigenPrice | null; ad_url?: string | null; images?: KleinanzeigenImage[] | null; created_at?: string | null; location?: { id?: string | null; name?: string | null; city?: string | null; zip?: string | null } | null; category?: { id?: string | null; name?: string | null } | null; attributes?: unknown[] | null; details?: JsonRecord | null };
export type KleinanzeigenSearchResponse = { success: boolean; data?: { meta?: JsonRecord; ads?: KleinanzeigenAd[] }; error_code?: string; request_id?: string };
export type DealFinderDataLevel = "search" | "detail";
export type IngestListing = { platform: "kleinanzeigen"; external_id: string; source_url: string; title: string; description: string | null; price: number | null; currency: string; brand: string | null; model: string | null; variant: string | null; year: number | null; mileage: number | null; fuel_type: string | null; transmission: string | null; power_kw: number | null; power_hp: number | null; city: string | null; postal_code: string | null; source_image_url: string | null; source_images: string[]; published_at: string | null; content_hash: string; data_level: DealFinderDataLevel; provider_detail_loaded: boolean; provider_detail_fetched_at: string | null; raw_data: JsonRecord };
export type IngestResponse = { created: number; updated: number; duplicates: number; rejected: number; created_listing_ids: number[] };
export type TouchSeenResponse = { touched: number; missing: number; missing_external_ids: string[] };
export type SyncMetadata = { candidates_found: number; new_candidates: number; existing_candidates: number; details_fetched: number; detail_failures: number; touched: number; rejected: number };
export type TouchSeenInput = { platform: "kleinanzeigen"; searchId: number; seenAt: string; externalIds: string[]; logSync?: boolean; syncMetadata?: SyncMetadata };
export type SyncResult = { dryRun: boolean; searches: number; candidates: number; newCandidates: number; existingCandidates: number; detailsFetched: number; detailFailures: number; touched: number; touchMissing: number; ingested?: IngestResponse };
