import type { Locale } from "./locales.ts";
import { translateArTrRecord } from "./arTrTranslations.ts";
import { translateFrCoreRecord } from "./frCoreTranslations.ts";

const ru = {
  title: "Автомобили", description: "Каталог проверенных автомобилей SiteCraft Auto Market", eyebrow: "Каталог автомобилей", lead: "Свежие проверенные объявления с фотографиями, ценами и быстрым поиском по главным параметрам.", view: "Вид каталога", grid: "Плитка", list: "Список", filters: "Фильтры каталога",
  smartSearch: "Умный подбор", aiTitle: "Найдите автомобиль одним запросом", aiLead: "Опишите задачу своими словами или сразу настройте параметры ниже.", query: "Запрос", queryPlaceholder: "Например: семейный дизель до 7000 € рядом с Braunschweig", aiSubmit: "Подобрать с AI · {count} кредит", resetAll: "Сбросить всё", saveSearch: "Сохранить поиск", aiPrivacy: "Изменение фильтров и просмотр каталога бесплатны. AI-кредит списывается только после успешного AI-разбора; при ошибке применяется бесплатный базовый разбор.", quickRefinements: "Быстрые уточнения", clarify: "Уточните выбор", clarifyLead: "Ответы сразу станут редактируемыми параметрами.", repeat: "Повторить", applied: "Применённые параметры", appliedLead: "Нажмите на параметр, чтобы убрать его.", allParameters: "Все параметры", manual: "Настроить подбор вручную",
  vehicleType: "Тип транспорта", bodyType: "Тип кузова", brand: "Марка", model: "Модель", city: "Город", priceFrom: "Цена от", priceTo: "Цена до", fuel: "Топливо", transmission: "Коробка", yearFrom: "Год от", yearTo: "Год до", mileageTo: "Пробег до", anyMasculine: "Любой", anyFeminine: "Любая", anyNeutral: "Любое", applyFree: "Применить бесплатно", reset: "Сбросить", cityExample: "Берлин",
  results: "Результаты", carsCount: "{count} авто", sort: "Сортировка", newest: "Сначала новые", cheaper: "Дешевле", expensive: "Дороже", lowerMileage: "Меньше пробег", sell: "Продать авто", loading: "Загружаю каталог автомобилей...", retry: "Обновить каталог", recommended: "Похожие на то, что вы смотрели", recommendedLead: "На основе просмотров на этом сайте.", missing: "Не указан",
  removeCriterion: "Убрать параметр {label}: {value}", emptyTitle: "По этим параметрам пока нет автомобилей", emptyLead: "Измените один критерий или сохраните поиск, чтобы вернуться к нему позже.", expandSearch: "Как расширить поиск", showAll: "Показать весь каталог", lastAiSearch: "Последний AI-поиск: {value}", queryRequired: "Напишите, какую машину ищете.", applyingFilters: "Подбираю фильтры...", apiMissing: "AI-поиск временно недоступен: API не настроен.", insufficientCredits: "Недостаточно AI-кредитов для подбора.", aiUnavailable: "AI-поиск временно недоступен. Повторите запрос.", aiConnectionFailed: "Не удалось связаться с AI-сервисом. Повторите запрос.", localFallback: "Применён локальный разбор запроса.", filtersApplied: "Фильтры применены.", noPublished: "Пока нет опубликованных объявлений.", cachedCatalog: "Каталог показан из сохранённой версии. Можно обновить список ещё раз.", catalogFailed: "Каталог временно не загрузился. Проверьте соединение и попробуйте ещё раз.", refreshing: "Обновляю каталог...", clarificationFailed: "Не удалось применить уточнение. Выберите параметр вручную.", loginToSave: "Войдите, чтобы сохранить поиск и позже получать похожие авто.", savedSearchesSoon: "Сохранённые поиски скоро появятся.", searchSaved: "Поиск сохранён.", repeatFailed: "Не удалось повторить последний поиск.", carFallback: "Автомобиль",
} as const;

export type CatalogMessages = Record<keyof typeof ru, string>;

const de: CatalogMessages = {
  title: "Autos", description: "Geprüfte Fahrzeuge auf dem SiteCraft Auto Market", eyebrow: "Fahrzeugkatalog", lead: "Aktuelle geprüfte Anzeigen mit Fotos, Preisen und schneller Suche nach den wichtigsten Merkmalen.", view: "Katalogansicht", grid: "Raster", list: "Liste", filters: "Katalogfilter",
  smartSearch: "Intelligente Suche", aiTitle: "Finden Sie ein Auto mit einer Anfrage", aiLead: "Beschreiben Sie Ihr Wunschauto oder stellen Sie die Parameter direkt ein.", query: "Anfrage", queryPlaceholder: "Zum Beispiel: Familien-Diesel bis 7000 € bei Braunschweig", aiSubmit: "Mit AI suchen · {count} Guthaben", resetAll: "Alles zurücksetzen", saveSearch: "Suche speichern", aiPrivacy: "Filter und Katalogansicht sind kostenlos. AI-Guthaben wird nur nach erfolgreicher Analyse berechnet; bei Fehlern wird die kostenlose lokale Analyse verwendet.", quickRefinements: "Schnelle Verfeinerungen", clarify: "Auswahl präzisieren", clarifyLead: "Antworten werden sofort zu bearbeitbaren Parametern.", repeat: "Wiederholen", applied: "Aktive Parameter", appliedLead: "Klicken Sie auf einen Parameter, um ihn zu entfernen.", allParameters: "Alle Parameter", manual: "Auswahl manuell einstellen",
  vehicleType: "Fahrzeugtyp", bodyType: "Karosserie", brand: "Marke", model: "Modell", city: "Ort", priceFrom: "Preis ab", priceTo: "Preis bis", fuel: "Kraftstoff", transmission: "Getriebe", yearFrom: "Baujahr ab", yearTo: "Baujahr bis", mileageTo: "Kilometer bis", anyMasculine: "Beliebig", anyFeminine: "Beliebig", anyNeutral: "Beliebig", applyFree: "Kostenlos anwenden", reset: "Zurücksetzen", cityExample: "Berlin",
  results: "Ergebnisse", carsCount: "{count} Autos", sort: "Sortierung", newest: "Neueste zuerst", cheaper: "Preis aufsteigend", expensive: "Preis absteigend", lowerMileage: "Wenigste Kilometer", sell: "Auto verkaufen", loading: "Fahrzeugkatalog wird geladen...", retry: "Katalog aktualisieren", recommended: "Ähnlich wie zuletzt angesehen", recommendedLead: "Basierend auf Ansichten auf dieser Website.", missing: "Nicht angegeben",
  removeCriterion: "Parameter {label}: {value} entfernen", emptyTitle: "Keine Fahrzeuge für diese Parameter", emptyLead: "Ändern Sie ein Kriterium oder speichern Sie die Suche für später.", expandSearch: "Suche erweitern", showAll: "Gesamten Katalog anzeigen", lastAiSearch: "Letzte AI-Suche: {value}", queryRequired: "Beschreiben Sie das gesuchte Auto.", applyingFilters: "Filter werden erstellt...", apiMissing: "AI-Suche ist vorübergehend nicht verfügbar: API ist nicht eingerichtet.", insufficientCredits: "Nicht genügend AI-Guthaben.", aiUnavailable: "AI-Suche ist vorübergehend nicht verfügbar. Bitte erneut versuchen.", aiConnectionFailed: "AI-Dienst nicht erreichbar. Bitte erneut versuchen.", localFallback: "Lokale Anfrageanalyse wurde verwendet.", filtersApplied: "Filter wurden angewendet.", noPublished: "Noch keine veröffentlichten Anzeigen.", cachedCatalog: "Gespeicherter Katalog wird angezeigt. Sie können erneut aktualisieren.", catalogFailed: "Katalog konnte nicht geladen werden. Verbindung prüfen und erneut versuchen.", refreshing: "Katalog wird aktualisiert...", clarificationFailed: "Verfeinerung konnte nicht angewendet werden. Bitte Parameter manuell wählen.", loginToSave: "Melden Sie sich an, um die Suche zu speichern und ähnliche Autos zu erhalten.", savedSearchesSoon: "Gespeicherte Suchen sind bald verfügbar.", searchSaved: "Suche gespeichert.", repeatFailed: "Die letzte Suche konnte nicht wiederholt werden.", carFallback: "Fahrzeug",
};

const uk: CatalogMessages = {
  title: "Автомобілі", description: "Каталог перевірених автомобілів SiteCraft Auto Market", eyebrow: "Каталог автомобілів", lead: "Свіжі перевірені оголошення з фотографіями, цінами та швидким пошуком за головними параметрами.", view: "Вигляд каталогу", grid: "Плитка", list: "Список", filters: "Фільтри каталогу",
  smartSearch: "Розумний підбір", aiTitle: "Знайдіть автомобіль одним запитом", aiLead: "Опишіть завдання своїми словами або налаштуйте параметри нижче.", query: "Запит", queryPlaceholder: "Наприклад: сімейний дизель до 7000 € біля Braunschweig", aiSubmit: "Підібрати з AI · {count} кредит", resetAll: "Скинути все", saveSearch: "Зберегти пошук", aiPrivacy: "Зміна фільтрів і перегляд каталогу безкоштовні. AI-кредит списується лише після успішного аналізу; у разі помилки застосовується безкоштовний локальний розбір.", quickRefinements: "Швидкі уточнення", clarify: "Уточніть вибір", clarifyLead: "Відповіді одразу стануть редагованими параметрами.", repeat: "Повторити", applied: "Застосовані параметри", appliedLead: "Натисніть параметр, щоб прибрати його.", allParameters: "Усі параметри", manual: "Налаштувати підбір вручну",
  vehicleType: "Тип транспорту", bodyType: "Тип кузова", brand: "Марка", model: "Модель", city: "Місто", priceFrom: "Ціна від", priceTo: "Ціна до", fuel: "Паливо", transmission: "Коробка", yearFrom: "Рік від", yearTo: "Рік до", mileageTo: "Пробіг до", anyMasculine: "Будь-який", anyFeminine: "Будь-яка", anyNeutral: "Будь-яке", applyFree: "Застосувати безкоштовно", reset: "Скинути", cityExample: "Берлін",
  results: "Результати", carsCount: "Авто: {count}", sort: "Сортування", newest: "Спочатку нові", cheaper: "Дешевші", expensive: "Дорожчі", lowerMileage: "Менший пробіг", sell: "Продати авто", loading: "Завантажую каталог автомобілів...", retry: "Оновити каталог", recommended: "Схожі на переглянуті", recommendedLead: "На основі переглядів на цьому сайті.", missing: "Не вказано",
  removeCriterion: "Прибрати параметр {label}: {value}", emptyTitle: "За цими параметрами автомобілів немає", emptyLead: "Змініть критерій або збережіть пошук на потім.", expandSearch: "Як розширити пошук", showAll: "Показати весь каталог", lastAiSearch: "Останній AI-пошук: {value}", queryRequired: "Напишіть, який автомобіль шукаєте.", applyingFilters: "Підбираю фільтри...", apiMissing: "AI-пошук тимчасово недоступний: API не налаштовано.", insufficientCredits: "Недостатньо AI-кредитів.", aiUnavailable: "AI-пошук тимчасово недоступний. Повторіть запит.", aiConnectionFailed: "Не вдалося зв’язатися з AI-сервісом. Повторіть запит.", localFallback: "Застосовано локальний розбір запиту.", filtersApplied: "Фільтри застосовано.", noPublished: "Поки немає опублікованих оголошень.", cachedCatalog: "Показано збережену версію каталогу. Можна оновити ще раз.", catalogFailed: "Каталог тимчасово не завантажився. Перевірте з’єднання.", refreshing: "Оновлюю каталог...", clarificationFailed: "Не вдалося застосувати уточнення. Виберіть параметр вручну.", loginToSave: "Увійдіть, щоб зберегти пошук і отримувати схожі авто.", savedSearchesSoon: "Збережені пошуки скоро з’являться.", searchSaved: "Пошук збережено.", repeatFailed: "Не вдалося повторити останній пошук.", carFallback: "Автомобіль",
};

const en: CatalogMessages = {
  title: "Cars", description: "Verified cars on SiteCraft Auto Market", eyebrow: "Vehicle catalogue", lead: "Fresh verified listings with photos, prices, and fast search across the main vehicle attributes.", view: "Catalogue view", grid: "Grid", list: "List", filters: "Catalogue filters",
  smartSearch: "Smart search", aiTitle: "Find a car with one request", aiLead: "Describe what you need or configure the parameters below.", query: "Request", queryPlaceholder: "For example: family diesel under €7,000 near Braunschweig", aiSubmit: "Search with AI · {count} credit", resetAll: "Reset all", saveSearch: "Save search", aiPrivacy: "Filters and catalogue browsing are free. AI credit is charged only after a successful AI analysis; a free local analysis is used if it fails.", quickRefinements: "Quick refinements", clarify: "Refine your choice", clarifyLead: "Answers immediately become editable parameters.", repeat: "Repeat", applied: "Applied parameters", appliedLead: "Select a parameter to remove it.", allParameters: "All parameters", manual: "Configure search manually",
  vehicleType: "Vehicle type", bodyType: "Body type", brand: "Make", model: "Model", city: "City", priceFrom: "Price from", priceTo: "Price to", fuel: "Fuel", transmission: "Transmission", yearFrom: "Year from", yearTo: "Year to", mileageTo: "Mileage to", anyMasculine: "Any", anyFeminine: "Any", anyNeutral: "Any", applyFree: "Apply for free", reset: "Reset", cityExample: "Berlin",
  results: "Results", carsCount: "{count} cars", sort: "Sort", newest: "Newest first", cheaper: "Lowest price", expensive: "Highest price", lowerMileage: "Lowest mileage", sell: "Sell a car", loading: "Loading vehicle catalogue...", retry: "Refresh catalogue", recommended: "Similar to cars you viewed", recommendedLead: "Based on views on this website.", missing: "Not provided",
  removeCriterion: "Remove parameter {label}: {value}", emptyTitle: "No cars match these parameters", emptyLead: "Change one criterion or save the search for later.", expandSearch: "Ways to expand the search", showAll: "Show full catalogue", lastAiSearch: "Last AI search: {value}", queryRequired: "Describe the car you are looking for.", applyingFilters: "Creating filters...", apiMissing: "AI search is temporarily unavailable: the API is not configured.", insufficientCredits: "Not enough AI credits.", aiUnavailable: "AI search is temporarily unavailable. Try again.", aiConnectionFailed: "Could not reach the AI service. Try again.", localFallback: "Local request analysis was applied.", filtersApplied: "Filters applied.", noPublished: "There are no published listings yet.", cachedCatalog: "A saved catalogue is shown. You can refresh it again.", catalogFailed: "The catalogue could not be loaded. Check your connection and try again.", refreshing: "Refreshing catalogue...", clarificationFailed: "Could not apply the refinement. Select a parameter manually.", loginToSave: "Sign in to save the search and receive similar cars later.", savedSearchesSoon: "Saved searches are coming soon.", searchSaved: "Search saved.", repeatFailed: "Could not repeat the last search.", carFallback: "Vehicle",
};

const dictionaries: Record<Locale, CatalogMessages> = {
  de,
  ru,
  uk,
  en,
  ar: translateArTrRecord(ru, "ar"),
  tr: translateArTrRecord(ru, "tr"),
  fr: translateFrCoreRecord(en),
};
export const getCatalogMessages = (locale: Locale) => dictionaries[locale] || dictionaries.en;
