import type { Locale } from "./locales.ts";
import { translateArTrRecord } from "./arTrTranslations.ts";

const ru = {
  buyIn: "{brand} {model} {year} купить в {city}", seoMileage: "пробег {value} км", datePending: "дата уточняется", newListing: "Новое объявление", viewsCount: "{count} просмотров", forSale: "В продаже", dealer: "Дилер", privateSeller: "Частный продавец", seller: "Продавец", carSeller: "Продавец автомобиля", promoted: "Продвигается", sold: "Автомобиль продан", contactSeller: "Связаться с продавцом",
  previousPhoto: "Предыдущее фото", nextPhoto: "Следующее фото", fullscreenPhoto: "Открыть фото на весь экран", photoNumber: "Фото {count}", characteristics: "Характеристики", allSpecs: "Все характеристики автомобиля", fromSeller: "От продавца", description: "Описание автомобиля", noDescription: "Продавец пока не добавил описание автомобиля.", translationApplied: "Автоматический перевод с языка: {language}.", translationFallback: "Перевод пока недоступен. Показан оригинал на языке: {language}.",
  mainData: "Основные данные", priceLocation: "Цена и местоположение", engineTransmission: "Двигатель и трансмиссия", bodyCapacity: "Кузов и вместимость", mileageHistory: "Пробег и история", vehicleType: "Тип транспорта", brand: "Марка", model: "Модель", year: "Год", productionYear: "Год выпуска", firstRegistration: "Первая регистрация", condition: "Состояние", sellerType: "Тип продавца", price: "Цена", currency: "Валюта", city: "Город", country: "Страна", fuel: "Топливо", engineVolume: "Объём двигателя", transmission: "Коробка", drivetrain: "Привод", body: "Кузов", color: "Цвет", doors: "Двери", seats: "Места", mileage: "Пробег", owners: "Владельцы", publishedAt: "Дата публикации", updatedAt: "Дата обновления", notProvided: "Не указано продавцом", kilometre: "км",
  aiSaw: "Что AI увидел в объявлении", aiHighlightsDisclaimer: "AI Highlights основаны на данных объявления и не заменяют техническую проверку автомобиля.", aiAnalysis: "AI-анализ объявления", aiAnalysisLead: "AI-оценка показывает качество заполнения объявления, а не техническое состояние автомобиля.", listingQuality: "Качество объявления", photoQuality: "Качество фото", dataTrust: "Доверие к данным", reviewStatus: "Статус проверки", notCalculated: "не рассчитано", needsClarification: "нужно уточнить", dataComplete: "данные заполнены", sellerRecommendations: "Рекомендации продавцу", noCriticalRecommendations: "Критичных рекомендаций нет.", warnings: "Предупреждения", clarifyField: "Уточните поле: {value}", noSeriousWarnings: "Серьезных предупреждений нет.", goodCompleteness: "Хорошая заполненность объявления", dataNeedsClarification: "Данные требуют уточнения", lowMileage: "Низкий пробег по данным объявления", economicalDiesel: "Экономичный дизель",
  sellerContacts: "Контакты продавца", contactSafety: "Используйте только способы связи, которые продавец сделал публичными.", call: "Позвонить", email: "Написать email", close: "Закрыть", noPublicContact: "Продавец пока не добавил публичный способ связи.", emailSubject: "Вопрос по объявлению {value}", activeListings: "{count} активных объявлений", shortListings: "{count} объявл.", otherSellerCars: "Другие автомобили продавца", availableCount: "{count} из доступных", similarCars: "Похожие автомобили", sameBrand: "Та же марка", similarBody: "Похожий кузов", sameFuel: "То же топливо", sameCity: "Тот же город", similarYear: "Похожий год", similarBudget: "Похожий бюджет", similarListing: "Похожее объявление",
  ownersCount: "{count} владельцев", doorsCount: "{count} дверей", seatsCount: "{count} мест", validTuv: "Действующий TÜV / HU", tuvUntil: "до {value}", noValidTuv: "Нет действующего TÜV / HU", save: "Сохранить", removeSaved: "Удалить из сохранённых",
  statusDraft: "Черновик", statusAiDraft: "AI-черновик", statusReady: "Готово к проверке", statusPending: "На модерации", statusApproved: "Проверено", statusPublished: "Опубликовано", statusRejected: "Отклонено", statusNeedsFix: "Нужно исправить", statusArchived: "В архиве", statusBlocked: "Заблокировано", statusDeleted: "Удалено", statusSold: "Продано",
} as const;
export type DetailMessages = Record<keyof typeof ru, string>;

const de: DetailMessages = {
  buyIn: "{brand} {model} {year} in {city} kaufen", seoMileage: "{value} km Laufleistung", datePending: "Datum wird geklärt", newListing: "Neue Anzeige", viewsCount: "{count} Aufrufe", forSale: "Zum Verkauf", dealer: "Händler", privateSeller: "Privatverkäufer", seller: "Verkäufer", carSeller: "Fahrzeugverkäufer", promoted: "Gesponsert", sold: "Fahrzeug verkauft", contactSeller: "Verkäufer kontaktieren",
  previousPhoto: "Vorheriges Foto", nextPhoto: "Nächstes Foto", fullscreenPhoto: "Foto im Vollbild öffnen", photoNumber: "Foto {count}", characteristics: "Fahrzeugdaten", allSpecs: "Alle Fahrzeugdaten", fromSeller: "Vom Verkäufer", description: "Fahrzeugbeschreibung", noDescription: "Der Verkäufer hat noch keine Fahrzeugbeschreibung hinzugefügt.", translationApplied: "Automatisch übersetzt aus: {language}.", translationFallback: "Die Übersetzung ist noch nicht verfügbar. Das Original wird angezeigt: {language}.",
  mainData: "Grunddaten", priceLocation: "Preis und Standort", engineTransmission: "Motor und Getriebe", bodyCapacity: "Karosserie und Kapazität", mileageHistory: "Laufleistung und Historie", vehicleType: "Fahrzeugtyp", brand: "Marke", model: "Modell", year: "Jahr", productionYear: "Baujahr", firstRegistration: "Erstzulassung", condition: "Zustand", sellerType: "Verkäufertyp", price: "Preis", currency: "Währung", city: "Ort", country: "Land", fuel: "Kraftstoff", engineVolume: "Hubraum", transmission: "Getriebe", drivetrain: "Antrieb", body: "Karosserie", color: "Farbe", doors: "Türen", seats: "Sitzplätze", mileage: "Kilometer", owners: "Fahrzeughalter", publishedAt: "Veröffentlicht", updatedAt: "Aktualisiert", notProvided: "Vom Verkäufer nicht angegeben", kilometre: "km",
  aiSaw: "Was AI in der Anzeige erkannt hat", aiHighlightsDisclaimer: "AI Highlights basieren auf Anzeigendaten und ersetzen keine technische Fahrzeugprüfung.", aiAnalysis: "AI-Anzeigenanalyse", aiAnalysisLead: "Die AI-Bewertung beurteilt die Vollständigkeit der Anzeige, nicht den technischen Fahrzeugzustand.", listingQuality: "Anzeigenqualität", photoQuality: "Fotoqualität", dataTrust: "Datenvertrauen", reviewStatus: "Prüfstatus", notCalculated: "nicht berechnet", needsClarification: "Klärung erforderlich", dataComplete: "Daten vollständig", sellerRecommendations: "Empfehlungen an den Verkäufer", noCriticalRecommendations: "Keine wichtigen Empfehlungen.", warnings: "Hinweise", clarifyField: "Feld klären: {value}", noSeriousWarnings: "Keine wichtigen Hinweise.", goodCompleteness: "Anzeige gut ausgefüllt", dataNeedsClarification: "Daten müssen geklärt werden", lowMileage: "Niedrige Laufleistung laut Anzeige", economicalDiesel: "Sparsamer Diesel",
  sellerContacts: "Verkäuferkontakt", contactSafety: "Nutzen Sie nur die vom Verkäufer veröffentlichten Kontaktwege.", call: "Anrufen", email: "E-Mail schreiben", close: "Schließen", noPublicContact: "Der Verkäufer hat noch keinen öffentlichen Kontakt angegeben.", emailSubject: "Frage zur Anzeige {value}", activeListings: "{count} aktive Anzeigen", shortListings: "{count} Anzeigen", otherSellerCars: "Weitere Fahrzeuge des Verkäufers", availableCount: "{count} verfügbar", similarCars: "Ähnliche Fahrzeuge", sameBrand: "Gleiche Marke", similarBody: "Ähnliche Karosserie", sameFuel: "Gleicher Kraftstoff", sameCity: "Gleicher Ort", similarYear: "Ähnliches Baujahr", similarBudget: "Ähnliches Budget", similarListing: "Ähnliche Anzeige",
  ownersCount: "{count} Fahrzeughalter", doorsCount: "{count} Türen", seatsCount: "{count} Sitzplätze", validTuv: "Gültiger TÜV / HU", tuvUntil: "gültig bis {value}", noValidTuv: "Kein gültiger TÜV / HU", save: "Speichern", removeSaved: "Aus gespeicherten entfernen",
  statusDraft: "Entwurf", statusAiDraft: "AI-Entwurf", statusReady: "Prüfbereit", statusPending: "In Moderation", statusApproved: "Geprüft", statusPublished: "Veröffentlicht", statusRejected: "Abgelehnt", statusNeedsFix: "Korrektur nötig", statusArchived: "Archiviert", statusBlocked: "Gesperrt", statusDeleted: "Gelöscht", statusSold: "Verkauft",
};

const uk: DetailMessages = {
  buyIn: "Купити {brand} {model} {year} у місті {city}", seoMileage: "пробіг {value} км", datePending: "дата уточнюється", newListing: "Нове оголошення", viewsCount: "{count} переглядів", forSale: "У продажу", dealer: "Дилер", privateSeller: "Приватний продавець", seller: "Продавець", carSeller: "Продавець автомобіля", promoted: "Просувається", sold: "Автомобіль продано", contactSeller: "Зв’язатися з продавцем",
  previousPhoto: "Попереднє фото", nextPhoto: "Наступне фото", fullscreenPhoto: "Відкрити фото на весь екран", photoNumber: "Фото {count}", characteristics: "Характеристики", allSpecs: "Усі характеристики автомобіля", fromSeller: "Від продавця", description: "Опис автомобіля", noDescription: "Продавець ще не додав опис автомобіля.", translationApplied: "Автоматично перекладено з мови: {language}.", translationFallback: "Переклад поки недоступний. Показано оригінал мовою: {language}.",
  mainData: "Основні дані", priceLocation: "Ціна та місцезнаходження", engineTransmission: "Двигун і трансмісія", bodyCapacity: "Кузов і місткість", mileageHistory: "Пробіг та історія", vehicleType: "Тип транспорту", brand: "Марка", model: "Модель", year: "Рік", productionYear: "Рік випуску", firstRegistration: "Перша реєстрація", condition: "Стан", sellerType: "Тип продавця", price: "Ціна", currency: "Валюта", city: "Місто", country: "Країна", fuel: "Паливо", engineVolume: "Об’єм двигуна", transmission: "Коробка", drivetrain: "Привід", body: "Кузов", color: "Колір", doors: "Двері", seats: "Місця", mileage: "Пробіг", owners: "Власники", publishedAt: "Дата публікації", updatedAt: "Дата оновлення", notProvided: "Не вказано продавцем", kilometre: "км",
  aiSaw: "Що AI побачив в оголошенні", aiHighlightsDisclaimer: "AI Highlights базуються на даних оголошення й не замінюють технічну перевірку автомобіля.", aiAnalysis: "AI-аналіз оголошення", aiAnalysisLead: "AI-оцінка показує якість заповнення оголошення, а не технічний стан автомобіля.", listingQuality: "Якість оголошення", photoQuality: "Якість фото", dataTrust: "Довіра до даних", reviewStatus: "Статус перевірки", notCalculated: "не розраховано", needsClarification: "потрібно уточнити", dataComplete: "дані заповнені", sellerRecommendations: "Рекомендації продавцю", noCriticalRecommendations: "Критичних рекомендацій немає.", warnings: "Попередження", clarifyField: "Уточніть поле: {value}", noSeriousWarnings: "Серйозних попереджень немає.", goodCompleteness: "Оголошення добре заповнене", dataNeedsClarification: "Дані потребують уточнення", lowMileage: "Низький пробіг за даними оголошення", economicalDiesel: "Економний дизель",
  sellerContacts: "Контакти продавця", contactSafety: "Використовуйте лише способи зв’язку, які продавець зробив публічними.", call: "Зателефонувати", email: "Написати email", close: "Закрити", noPublicContact: "Продавець ще не додав публічний спосіб зв’язку.", emailSubject: "Питання щодо оголошення {value}", activeListings: "Активних оголошень: {count}", shortListings: "Оголошень: {count}", otherSellerCars: "Інші автомобілі продавця", availableCount: "Доступно: {count}", similarCars: "Схожі автомобілі", sameBrand: "Та сама марка", similarBody: "Схожий кузов", sameFuel: "Те саме паливо", sameCity: "Те саме місто", similarYear: "Схожий рік", similarBudget: "Схожий бюджет", similarListing: "Схоже оголошення",
  ownersCount: "Власників: {count}", doorsCount: "Дверей: {count}", seatsCount: "Місць: {count}", validTuv: "Дійсний TÜV / HU", tuvUntil: "до {value}", noValidTuv: "Немає дійсного TÜV / HU", save: "Зберегти", removeSaved: "Видалити зі збережених",
  statusDraft: "Чернетка", statusAiDraft: "AI-чернетка", statusReady: "Готово до перевірки", statusPending: "На модерації", statusApproved: "Перевірено", statusPublished: "Опубліковано", statusRejected: "Відхилено", statusNeedsFix: "Потрібно виправити", statusArchived: "В архіві", statusBlocked: "Заблоковано", statusDeleted: "Видалено", statusSold: "Продано",
};

const en: DetailMessages = {
  buyIn: "Buy {brand} {model} {year} in {city}", seoMileage: "{value} km mileage", datePending: "date pending", newListing: "New listing", viewsCount: "{count} views", forSale: "For sale", dealer: "Dealer", privateSeller: "Private seller", seller: "Seller", carSeller: "Vehicle seller", promoted: "Promoted", sold: "Vehicle sold", contactSeller: "Contact seller",
  previousPhoto: "Previous photo", nextPhoto: "Next photo", fullscreenPhoto: "Open photo fullscreen", photoNumber: "Photo {count}", characteristics: "Specifications", allSpecs: "All vehicle specifications", fromSeller: "From the seller", description: "Vehicle description", noDescription: "The seller has not added a vehicle description yet.", translationApplied: "Automatically translated from: {language}.", translationFallback: "Translation is not available yet. Showing the original in: {language}.",
  mainData: "Main details", priceLocation: "Price and location", engineTransmission: "Engine and transmission", bodyCapacity: "Body and capacity", mileageHistory: "Mileage and history", vehicleType: "Vehicle type", brand: "Make", model: "Model", year: "Year", productionYear: "Production year", firstRegistration: "First registration", condition: "Condition", sellerType: "Seller type", price: "Price", currency: "Currency", city: "City", country: "Country", fuel: "Fuel", engineVolume: "Engine capacity", transmission: "Transmission", drivetrain: "Drivetrain", body: "Body", color: "Colour", doors: "Doors", seats: "Seats", mileage: "Mileage", owners: "Owners", publishedAt: "Published", updatedAt: "Updated", notProvided: "Not provided by seller", kilometre: "km",
  aiSaw: "What AI found in the listing", aiHighlightsDisclaimer: "AI Highlights are based on listing data and do not replace a technical vehicle inspection.", aiAnalysis: "AI listing analysis", aiAnalysisLead: "The AI score reflects listing completeness, not the vehicle’s technical condition.", listingQuality: "Listing quality", photoQuality: "Photo quality", dataTrust: "Data confidence", reviewStatus: "Review status", notCalculated: "not calculated", needsClarification: "clarification needed", dataComplete: "data complete", sellerRecommendations: "Recommendations for the seller", noCriticalRecommendations: "No critical recommendations.", warnings: "Warnings", clarifyField: "Clarify field: {value}", noSeriousWarnings: "No serious warnings.", goodCompleteness: "Listing is well completed", dataNeedsClarification: "Data needs clarification", lowMileage: "Low mileage according to the listing", economicalDiesel: "Economical diesel",
  sellerContacts: "Seller contacts", contactSafety: "Only use contact methods the seller has made public.", call: "Call", email: "Send email", close: "Close", noPublicContact: "The seller has not added a public contact method yet.", emailSubject: "Question about listing {value}", activeListings: "{count} active listings", shortListings: "{count} listings", otherSellerCars: "Other cars from this seller", availableCount: "{count} available", similarCars: "Similar cars", sameBrand: "Same make", similarBody: "Similar body", sameFuel: "Same fuel", sameCity: "Same city", similarYear: "Similar year", similarBudget: "Similar budget", similarListing: "Similar listing",
  ownersCount: "{count} owners", doorsCount: "{count} doors", seatsCount: "{count} seats", validTuv: "Valid TÜV / HU", tuvUntil: "valid until {value}", noValidTuv: "No valid TÜV / HU", save: "Save", removeSaved: "Remove from saved",
  statusDraft: "Draft", statusAiDraft: "AI draft", statusReady: "Ready for review", statusPending: "In moderation", statusApproved: "Verified", statusPublished: "Published", statusRejected: "Rejected", statusNeedsFix: "Needs changes", statusArchived: "Archived", statusBlocked: "Blocked", statusDeleted: "Deleted", statusSold: "Sold",
};

const dictionaries: Record<Locale, DetailMessages> = {
  de,
  ru,
  uk,
  en,
  ar: translateArTrRecord(ru, "ar"),
  tr: translateArTrRecord(ru, "tr"),
};
export const getDetailMessages = (locale: Locale) => dictionaries[locale];
