import type {
  DealFinderAnalysis,
  DealFinderEmail,
  DealFinderListing,
  DealFinderSearch,
  DealFinderStats,
  DealFinderSyncLog,
} from "./types";

const now = "2026-07-16T09:30:00.000Z";

const completeAnalysis = (overrides: Partial<DealFinderAnalysis>): DealFinderAnalysis => ({
  id: 5000,
  listing_id: 0,
  status: "completed",
  positive_signals: [],
  negative_signals: [],
  missing_information: [],
  known_defects: [],
  recommended_questions: [],
  analysis_status: "completed",
  confidence_score: 0.7,
  model: "fixture-structured-output",
  completed_at: now,
  analyzed_at: now,
  ...overrides,
});

export const dealFinderMockSearches: DealFinderSearch[] = [
  {
    id: 101,
    name: "Гольфы до 4 000 EUR",
    platform: "kleinanzeigen",
    brand: "Volkswagen",
    model: "Golf",
    price_max: 4000,
    year_min: 2008,
    mileage_max: 220000,
    fuel_types: ["Diesel"],
    transmissions: [],
    required_keywords: ["TUV"],
    excluded_keywords: ["Bastler"],
    minimum_deal_score: 70,
    is_active: true,
    postal_code: "38100",
    radius_km: 100,
    created_at: now,
  },
];

export const dealFinderMockListings: DealFinderListing[] = [
  {
    id: 1001,
    user_id: 1,
    search_id: 101,
    platform: "kleinanzeigen",
    external_id: "df-test-new-001",
    source_url: "https://www.kleinanzeigen.de/s-anzeige/df-test-new-001",
    title: "Volkswagen Golf VI 1.6 TDI",
    description: "Тестовое внутреннее объявление. Требует проверки оригинального источника.",
    price: 2900,
    currency: "EUR",
    brand: "Volkswagen",
    model: "Golf",
    variant: "1.6 TDI",
    year: 2011,
    mileage: 186000,
    fuel_type: "Diesel",
    transmission: "Schaltgetriebe",
    power_kw: 77,
    city: "Braunschweig",
    postal_code: "38100",
    source_image_url: "https://images.example.invalid/deal-finder-golf-1.jpg",
    image_status: "unknown",
    first_seen_at: "2026-07-16T08:00:00.000Z",
    last_seen_at: now,
    source_status: "active",
    user_status: "new",
    unavailable_checks: 0,
    is_new: true,
    is_saved: false,
    is_viewed: false,
    is_hidden: false,
    analysis: completeAnalysis({ id: 5001, listing_id: 1001, deal_score: 74, recommendation: "REVIEW", ai_summary: "Данные выглядят полными для первичного звонка." }),
  },
  {
    id: 1002,
    user_id: 1,
    search_id: 101,
    platform: "kleinanzeigen",
    external_id: "df-test-hot-002",
    source_url: "https://www.kleinanzeigen.de/s-anzeige/df-test-hot-002",
    title: "Volkswagen Golf VII Variant 2.0 TDI",
    description: "Тестовое горячее предложение. Все решения принимаются после проверки источника.",
    price: 6200,
    currency: "EUR",
    brand: "Volkswagen",
    model: "Golf",
    variant: "Variant 2.0 TDI",
    year: 2015,
    mileage: 173000,
    fuel_type: "Diesel",
    transmission: "Automatik",
    power_kw: 110,
    city: "Hannover",
    postal_code: "30159",
    source_image_url: "https://images.example.invalid/deal-finder-golf-2.jpg",
    image_status: "unknown",
    first_seen_at: "2026-07-16T07:10:00.000Z",
    last_seen_at: now,
    source_status: "active",
    user_status: "new",
    unavailable_checks: 0,
    is_new: true,
    is_saved: false,
    is_viewed: false,
    is_hidden: false,
    analysis: completeAnalysis({ id: 5002, listing_id: 1002, deal_score: 86, recommendation: "HOT_DEAL", potential_profit_low: 900, potential_profit_high: 1700, ai_summary: "Тестовая оценка: приоритетно проверить источник и состояние." }),
  },
  {
    id: 1003,
    user_id: 1,
    platform: "kleinanzeigen",
    external_id: "df-test-saved-003",
    source_url: "https://www.kleinanzeigen.de/s-anzeige/df-test-saved-003",
    title: "Mercedes-Benz C 220 CDI",
    price: 4800,
    currency: "EUR",
    brand: "Mercedes-Benz",
    model: "C 220",
    year: 2010,
    mileage: 212000,
    fuel_type: "Diesel",
    transmission: "Automatik",
    city: "Wolfsburg",
    source_image_url: "https://images.example.invalid/deal-finder-mercedes.jpg",
    image_status: "unknown",
    first_seen_at: "2026-07-15T12:00:00.000Z",
    last_seen_at: now,
    source_status: "active",
    user_status: "saved",
    unavailable_checks: 0,
    is_new: false,
    is_saved: true,
    is_viewed: true,
    is_hidden: false,
    analysis: completeAnalysis({ id: 5003, listing_id: 1003, deal_score: 76, recommendation: "CONTACT_NOW" }),
  },
  {
    id: 1004,
    user_id: 1,
    platform: "kleinanzeigen",
    external_id: "df-test-hidden-004",
    source_url: "https://www.kleinanzeigen.de/s-anzeige/df-test-hidden-004",
    title: "Audi A4 Avant 2.0 TDI",
    price: 3900,
    currency: "EUR",
    brand: "Audi",
    model: "A4",
    year: 2009,
    mileage: 245000,
    fuel_type: "Diesel",
    transmission: "Schaltgetriebe",
    city: "Celle",
    image_status: "placeholder",
    first_seen_at: "2026-07-14T12:00:00.000Z",
    last_seen_at: now,
    source_status: "active",
    user_status: "hidden",
    unavailable_checks: 0,
    is_new: false,
    is_saved: false,
    is_viewed: true,
    is_hidden: true,
    analysis: completeAnalysis({ id: 5004, listing_id: 1004, deal_score: 61, recommendation: "WATCH" }),
  },
  {
    id: 1005,
    user_id: 1,
    platform: "kleinanzeigen",
    external_id: "df-test-removed-005",
    source_url: "https://www.kleinanzeigen.de/s-anzeige/df-test-removed-005",
    title: "BMW 320d Touring",
    price: 5100,
    currency: "EUR",
    brand: "BMW",
    model: "320d",
    year: 2012,
    mileage: 238000,
    fuel_type: "Diesel",
    transmission: "Automatik",
    city: "Gifhorn",
    image_status: "placeholder",
    first_seen_at: "2026-07-13T10:00:00.000Z",
    last_seen_at: "2026-07-14T10:00:00.000Z",
    last_checked_at: "2026-07-16T08:00:00.000Z",
    source_status: "source_removed",
    user_status: "saved",
    unavailable_checks: 3,
    is_new: false,
    is_saved: true,
    is_viewed: true,
    is_hidden: true,
    analysis: completeAnalysis({ id: 5005, listing_id: 1005, deal_score: 82, recommendation: "WATCH", ai_summary: "Источник больше не доступен; запись сохранена для истории." }),
  },
  {
    id: 1006,
    user_id: 1,
    platform: "kleinanzeigen",
    external_id: "df-test-pending-006",
    source_url: "https://www.kleinanzeigen.de/s-anzeige/df-test-pending-006",
    title: "Skoda Octavia Combi",
    price: 3400,
    currency: "EUR",
    brand: "Skoda",
    model: "Octavia",
    year: 2010,
    mileage: 198000,
    fuel_type: "Diesel",
    transmission: "Schaltgetriebe",
    city: "Peine",
    image_status: "placeholder",
    first_seen_at: "2026-07-16T06:00:00.000Z",
    last_seen_at: now,
    source_status: "active",
    user_status: "new",
    unavailable_checks: 0,
    is_new: true,
    is_saved: false,
    is_viewed: false,
    is_hidden: false,
    analysis: null,
  },
];

export const dealFinderMockEmails: DealFinderEmail[] = [];

export const dealFinderMockSyncLogs: DealFinderSyncLog[] = [
  {
    id: 7001,
    job_type: "manual_seed",
    status: "completed",
    emails_found: 0,
    emails_processed: 0,
    listings_found: 6,
    listings_created: 6,
    listings_updated: 0,
    duplicates_found: 0,
    listings_removed: 0,
    started_at: "2026-07-16T09:00:00.000Z",
    finished_at: "2026-07-16T09:00:01.000Z",
  },
];

export function getDealFinderMockStats(): DealFinderStats {
  return {
    active: dealFinderMockListings.filter((listing) => listing.source_status === "active" && !listing.is_hidden).length,
    new: dealFinderMockListings.filter((listing) => listing.is_new).length,
    saved: dealFinderMockListings.filter((listing) => listing.is_saved).length,
    hidden: dealFinderMockListings.filter((listing) => listing.is_hidden).length,
    hot: dealFinderMockListings.filter((listing) => (listing.analysis?.deal_score || 0) >= 80).length,
    analysis_pending: dealFinderMockListings.filter((listing) => !listing.analysis || listing.analysis.status === "pending" || listing.analysis.status === "processing").length,
    source_removed: dealFinderMockListings.filter((listing) => listing.source_status === "source_removed").length,
  };
}
